# Generated by Django 2.1.2 on 2019-01-13 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeproduct',
            name='interest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scraper.Interest'),
            preserve_default=False,
        ),
    ]
