# Generated by Django 2.1.2 on 2019-01-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scrapeproduct_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeproduct',
            name='image_url',
            field=models.URLField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeproduct',
            name='url',
            field=models.URLField(max_length=800),
        ),
    ]
