# Generated by Django 2.1.2 on 2019-01-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20190113_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeproduct',
            name='image_url',
            field=models.URLField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeproduct',
            name='url',
            field=models.URLField(max_length=4000),
        ),
    ]
