# Generated by Django 2.1.2 on 2018-11-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0002_gifteeprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifteeprofile',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
