# Generated by Django 2.1.2 on 2018-11-10 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0003_gifteeprofile_fulfilled'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.TextField()),
                ('link', models.URLField()),
                ('giftee_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ideas', to='forgyftapp.GifteeProfile')),
            ],
        ),
    ]
