# Generated by Django 2.1.2 on 2018-11-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0004_auto_20181117_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftidea',
            name='explanation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
