# Generated by Django 2.1.2 on 2018-11-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0005_giftidea_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifteeprofile',
            name='emailed_about_publish',
            field=models.BooleanField(default=False),
        ),
    ]
