# Generated by Django 2.1.2 on 2018-11-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0005_auto_20181110_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifteeprofile',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gifteeprofile',
            name='existing_related_items',
            field=models.TextField(default='', max_length=6000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gifteeprofile',
            name='extra_info',
            field=models.TextField(default='', max_length=6000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gifteeprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gifteeprofile',
            name='price_upper',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gifteeprofile',
            name='relationship',
            field=models.TextField(default='Friend', max_length=6000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gifteeprofile',
            name='interests',
            field=models.TextField(max_length=6000),
        ),
    ]
