# Generated by Django 2.1.2 on 2018-11-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0006_gifteeprofile_emailed_about_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifteeprofile',
            name='occasion',
            field=models.TextField(default='', max_length=6000),
            preserve_default=False,
        ),
    ]
