# Generated by Django 2.1.2 on 2018-11-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0007_giftidea_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifteeprofile',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
