# Generated by Django 2.1.2 on 2018-11-28 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0007_gifteeprofile_occasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftidea',
            name='giftee_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='forgyftapp.GifteeProfile'),
        ),
    ]
