# Generated by Django 2.1.2 on 2018-11-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0008_auto_20181128_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftidea',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
