# Generated by Django 2.1.2 on 2018-11-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0008_gifteeprofile_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifteeprofile',
            name='name',
            field=models.TextField(default='bob', max_length=150),
            preserve_default=False,
        ),
    ]
