# Generated by Django 2.1.2 on 2018-11-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0009_gifteeprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gifteeprofile',
            name='fulfilled',
        ),
    ]
