# Generated by Django 2.1.2 on 2018-11-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0010_giftidea_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftidea',
            name='image',
            field=models.URLField(blank=True, max_length=2400, null=True),
        ),
        migrations.AlterField(
            model_name='giftidea',
            name='link',
            field=models.URLField(max_length=2400),
        ),
    ]
