# Generated by Django 2.1.2 on 2018-12-02 01:29

from django.db import migrations, models
import django.db.models.deletion
import forgyftapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0011_auto_20181130_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField(max_length=6000)),
                ('bought', models.BooleanField()),
            ],
            bases=(models.Model, forgyftapp.models.OnCreate),
        ),
        migrations.AddField(
            model_name='gifteeprofile',
            name='feedback',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forgyftapp.GiftFeedback'),
        ),
    ]
