# Generated by Django 2.1.2 on 2018-12-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0014_gifteeprofile_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifteeprofile',
            name='ip_address',
            field=models.GenericIPAddressField(default=None, null=True),
        ),
    ]
