# Generated by Django 2.1.2 on 2018-12-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0015_gifteeprofile_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifteeprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
