# Generated by Django 2.1.2 on 2018-12-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0018_gifteeprofile__slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifteeprofile',
            name='_location',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
