# Generated by Django 2.1.2 on 2019-01-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0019_gifteeprofile__location'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifteeprofile',
            name='scraper_interests',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
