# Generated by Django 2.1.2 on 2019-01-12 23:12

from django.db import migrations, models
import django.db.models.deletion
import forgyftapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0020_gifteeprofile_scraper_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.TextField(blank=True, default=None, null=True)),
            ],
            bases=(models.Model, forgyftapp.models.OnCreate),
        ),
        migrations.AlterField(
            model_name='gifteeprofile',
            name='scraper_interests',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forgyftapp.ScraperInterests'),
        ),
    ]
