# Generated by Django 2.1.2 on 2019-01-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0021_auto_20190112_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperinterests',
            name='generated',
            field=models.BooleanField(default=False),
        ),
    ]
