# Generated by Django 2.1.2 on 2019-01-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
        ('forgyftapp', '0022_scraperinterests_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperinterests',
            name='interest_objects',
            field=models.ManyToManyField(to='scraper.Interest'),
        ),
    ]
