# Generated by Django 2.1.2 on 2019-01-13 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0024_remove_scraperinterests_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifteeprofile',
            name='feedback',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forgyftapp.GiftFeedback'),
        ),
        migrations.AlterField(
            model_name='gifteeprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
