# Generated by Django 2.1.2 on 2019-01-13 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0025_auto_20190113_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifteeprofile',
            name='scraper_interests',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forgyftapp.ScraperInterests'),
        ),
    ]
