# Generated by Django 2.1.2 on 2019-01-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0026_auto_20190113_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expert_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='expert_interests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
