# Generated by Django 2.1.2 on 2019-01-31 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0027_auto_20190131_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleGiftRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='expert_sample_gift_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forgyftapp.SampleGiftRequest'),
        ),
    ]
