# Generated by Django 2.1.2 on 2019-02-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0028_auto_20190131_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplegiftrequest',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplegiftrequest',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplegiftrequest',
            name='interests',
            field=models.TextField(default=None, max_length=6000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplegiftrequest',
            name='occasion',
            field=models.TextField(default=None, max_length=6000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplegiftrequest',
            name='price_upper',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplegiftrequest',
            name='relationship',
            field=models.TextField(default=None, max_length=6000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_expert',
            field=models.BooleanField(default=False),
        ),
    ]
