# Generated by Django 2.1.2 on 2019-02-03 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0030_user_expert_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='expert_sample_gift_request',
            new_name='_expert_sample_gift_request',
        ),
    ]
