# Generated by Django 2.1.2 on 2019-02-05 03:48

from django.db import migrations, models
import django.db.models.deletion
import forgyftapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0031_auto_20190203_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleGiftIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.TextField()),
                ('link', models.URLField(max_length=2400)),
                ('image', models.URLField(blank=True, max_length=2400, null=True)),
                ('explanation', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('clicks', models.IntegerField(default=0)),
                ('sample_giftee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='forgyftapp.SampleGiftRequest')),
            ],
            bases=(models.Model, forgyftapp.models.OnCreate),
        ),
    ]
