# Generated by Django 2.1.2 on 2019-02-05 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0033_samplegiftrequest_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expert_requests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert', to='forgyftapp.GifteeProfile'),
        ),
    ]
