# Generated by Django 2.1.2 on 2019-02-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0035_auto_20190205_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifteeprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
