# Generated by Django 2.1.2 on 2019-02-05 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0036_auto_20190205_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifteeprofile',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
