# Generated by Django 2.1.2 on 2019-04-17 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0037_auto_20190205_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='demo_fulfill',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gifteeprofile',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_request_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
