# Generated by Django 2.1.2 on 2019-04-14 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0037_auto_20190205_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifteeprofile',
            name='personality_traits',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='gifteeprofile',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_request_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
