# Generated by Django 2.1.2 on 2019-04-17 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0038_auto_20190414_1742'),
        ('forgyftapp', '0038_auto_20190417_0057'),
    ]

    operations = [
    ]
