# Generated by Django 2.1.2 on 2019-04-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0039_merge_20190417_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftfeedback',
            name='bought',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
