# Generated by Django 2.1.2 on 2019-04-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgyftapp', '0040_auto_20190424_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expert_gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=80, null=True),
        ),
    ]
